# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="mytheme"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="false"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"
#
# Make vi-mode react quicker on ESC key
KEYTIMEOUT=1

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_AUTOCONNECT=false

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git tmux django zsh-completions bgnotify)

# User configuration

export PATH=$HOME/bin:/usr/local/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh


# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias tmux="TERM=screen-256color-bce tmux"
alias v='\vim'
alias vim='echo "Use v instead"'

bindkey '^R' history-incremental-pattern-search-backward
bindkey -M vicmd v edit-command-line

source ~/.secret.sh

export HTTPS_PROXY=$PROXY
export HTTP_PROXY=$PROXY
export FTP_PROXY=$PROXY
export https_proxy=$PROXY
export http_proxy=$PROXY
export ftp_proxy=$PROXY
export NO_PROXY="localhost,127.0.0.1"
export no_proxy="localhost,127.0.0.1"
export WORKSPACE=$HOME/aginoodle
export EDITOR=vim
export FT=$WORKSPACE/src/backlog/tests/feature_tests/
export MT=$WORKSPACE/src/backlog/tests/module_tests/
export UT=$WORKSPACE/src/backlog/tests/unit_tests/

function t() {
    (cd $WORKSPACE; script -c "bin/py.test --reuse-db $1" /tmp/tests.log)
}

function show_tests() {
    grep "def test" $1 | sort | grep "test"
}

alias IWONA_PAVLOVIC="pylint --rcfile=$WORKSPACE/config/pylint.cfg --msg-template='{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}'"
alias agi="cd $WORKSPACE"
alias atd="cd $WORKSPACE/src/backlog/tests"
alias ft="t src/backlog/tests/feature_tests/"
alias mt="t src/backlog/tests/module_tests/"
alias ut="t src/backlog/tests/unit_tests/"
alias jt='(cd $WORKSPACE/src/backlog/; ../../bin/jasmine-ci)'
alias jasmine='(cd $WORKSPACE/src/backlog/; ../../bin/jasmine)'
alias at='runall'
alias backlog="$WORKSPACE/bin/backlog"
alias shell="$WORKSPACE/bin/backlog shell_plus --bpython"
alias mysql='mycli'
alias glonull='ssh dev-aginoodle@glonull3.dynamic.nsn-net.net'
alias stelle='(cd $WORKSPACE; ../AginoodleStelle/stelle_run.py)'
alias teamcal='(cd $HOME/teamcal; php -S localhost:5000 -t .)'

function runall() {
    cd $WORKSPACE
    bin/fab clean_pyc
    tmux split-window -t:.0
    tmux split-window -h -t:.1
    tmux split-window -h -t:.0

    tmux send-keys -t:.0 ut
    tmux send-keys -t:.0 Enter
    tmux resize-pane -t:.0 -y 15

    tmux send-keys -t:.1 mt
    tmux send-keys -t:.1 Enter

    tmux send-keys -t:.2 stelle
    tmux send-keys -t:.2 Enter

    tmux send-keys -t:.3 jt
    tmux send-keys -t:.3 Enter
}

source $HOME/dotfiles/base16-default.dark.sh

alias grh='git reset'
alias grH='git reset --hard'
alias grh^='git reset HEAD^'
alias grH^='git reset --hard HEAD^'
alias gcof='git checkout -f'

eval "$(fasd --init auto)"
# completition in bin/backlog - requires Oh-My-ZSH
compdef _managepy backlog
